// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBi5Hxgt9rW5pg_VbBGuah6iUnCKRhKXOQ',
    appId: '1:1481541931:web:9223d2ea4e45d672dadd6e',
    messagingSenderId: '1481541931',
    projectId: 'fresh-flow-habit',
    authDomain: 'fresh-flow-habit.firebaseapp.com',
    storageBucket: 'fresh-flow-habit.firebasestorage.app',
    measurementId: 'G-Y9WLWG40JV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUbfK6BBbAPfDNUnu0HgfRLu2awYDWB6A',
    appId: '1:1481541931:android:77d5004dab18354cdadd6e',
    messagingSenderId: '1481541931',
    projectId: 'fresh-flow-habit',
    storageBucket: 'fresh-flow-habit.firebasestorage.app',
  );

}